import { FRONTEND_LINKS } from "~/constants/links";
import { icons } from "./themes";

type MenuType = {
  label: string;
  children: {
    label: string;
    title: string;
    description: string;
    path: string;
    icon: string;
  }[];
  permission: string;
};

export const menu: MenuType[] = [
  {
    label: "",
    children: [
      {
        label: "Dashboard",
        title: "Dashboard",
        path: FRONTEND_LINKS.panels.dashboard,
        icon: icons.AnalyticsIcon1,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
    ],
    permission: "view_dashboard",
  },
  {
    label: "Product Management",
    children: [
      {
        label: "Products",
        title: "Products",
        path: FRONTEND_LINKS.panels.manageProducts.products.list,
        icon: icons.ProductIcon1,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Product Statuses",
        title: "Statuses",
        path: FRONTEND_LINKS.panels.manageProducts.statuses.list,
        icon: icons.ProductIcon2,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Inventory Types",
        title: "Types",
        path: FRONTEND_LINKS.panels.manageProducts.inventoryTypes.list,
        icon: icons.ProductIcon3,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Product Units",
        title: "Units",
        path: FRONTEND_LINKS.panels.manageProducts.units.list,
        icon: icons.ProductIcon4,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Product Categories",
        title: "Categories",
        path: FRONTEND_LINKS.panels.manageProducts.categories.list,
        icon: icons.ProductIcon5,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Brands",
        title: "Brands",
        path: FRONTEND_LINKS.panels.manageProducts.brands.list,
        icon: icons.ProductIcon6,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Product Mapping With Departments",
        title: "Product-Mapping",
        path: FRONTEND_LINKS.panels.manageProducts.productMapping.list,
        icon: icons.ProductIcon8,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Product Group",
        title: "Group",
        path: FRONTEND_LINKS.panels.manageProducts.productGroup.list,
        icon: icons.ProductIcon9,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Product Sub Group",
        title: "Sub Group",
        path: FRONTEND_LINKS.panels.manageProducts.productSubGroup.list,
        icon: icons.ProductIcon10,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
    ],
    permission: "manage_products",
  },
  {
    label: "Point of Sale (POS)",
    children: [
      {
        label: "Sale",
        title: "Sale",
        path: FRONTEND_LINKS.panels.pointOfSale.sales.create,
        icon: icons.PosIcon1,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Sale list",
        title: "Sale list",
        path: FRONTEND_LINKS.panels.pointOfSale.sales.list,
        icon: icons.PosIcon1,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Sales Report",
        title: "Sales Report",
        path: FRONTEND_LINKS.panels.pointOfSale.sales.report,
        icon: icons.providentFundReport,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Daily Report",
        title: "Daily Report",
        path: FRONTEND_LINKS.panels.pointOfSale.sales.dailyReport,
        icon: icons.daily,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Kot/Bot",
        title: "Kot/Bot",
        path: FRONTEND_LINKS.panels.pointOfSale.sales.kotBot,
        icon: icons.PosIcon4,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
    ],
    permission: "pos",
  },
  {
    label: "Customer Relation Management (CRM)",
    children: [
      {
        label: "Members",
        title: "Members",
        path: FRONTEND_LINKS.panels.customerRelationManagement.members.list,
        icon: icons.CrmIcon1,
        description: "Lorem ipsum dolor sit amet consectetur",
      },

      {
        label: "Membership Transfers",
        title: "Transfers",
        path: FRONTEND_LINKS.panels.customerRelationManagement
          .membershipTransfers.list,
        icon: icons.HotelIcon3,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Categories",
        title: "Categories",
        path: FRONTEND_LINKS.panels.customerRelationManagement.categories.list,
        icon: icons.CrmIcon2,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Member Expire Types",
        title: "Expire",
        path: FRONTEND_LINKS.panels.customerRelationManagement.expireTypes.list,
        icon: icons.CrmIcon3,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Member Titles",
        title: "Titles",
        path: FRONTEND_LINKS.panels.customerRelationManagement.memberTitles
          .list,
        icon: icons.employeeTitle,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Members Information View",
        title: "Members Information View",
        path: FRONTEND_LINKS.panels.customerRelationManagement
          .membersInformationView.list,
        icon: icons.CrmIcon1,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Members Reports",
        title: "Members Reports",
        path: FRONTEND_LINKS.panels.customerRelationManagement
          .membersInformationView.report,
        icon: icons.CrmIcon1,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
    ],
    permission: "crm",
  },
  {
    label: "Human Resource Management (HRM)",
    children: [
      {
        label: "Employees",
        title: "Employees",
        path: FRONTEND_LINKS.panels.humanResourceManagement.employees.list,
        icon: icons.HrmIcon1,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Department",
        title: "Department",
        path: FRONTEND_LINKS.panels.humanResourceManagement.departments.list,
        icon: icons.HrmIcon2,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Designations",
        title: "Designations",
        path: FRONTEND_LINKS.panels.humanResourceManagement.designations.list,
        icon: icons.HrmIcon3,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Employee Biography",
        title: "Employee Biography",
        path: FRONTEND_LINKS.panels.humanResourceManagement.employeeBiography
          .list,
        icon: icons.HrmIcon3,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Roles",
        title: "Roles",
        path: FRONTEND_LINKS.panels.humanResourceManagement.roles.list,
        icon: icons.HrmIcon4,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Employee Types",
        title: "Types",
        path: FRONTEND_LINKS.panels.humanResourceManagement.employeeTypes.list,
        icon: icons.employeeType,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Employee Titles",
        title: "Titles",
        path: FRONTEND_LINKS.panels.humanResourceManagement.employeeTitles.list,
        icon: icons.employeeTitle,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
    ],
    permission: "hrm",
  },
  {
    label: "Accounts",
    children: [
      {
        label: "Chart of Accounts",
        title: "Accounts",
        path: FRONTEND_LINKS.panels.accounts.chartOfAccounts.list,
        icon: icons.AccountIcon1,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Member Payments",
        title: "Payments",
        path: FRONTEND_LINKS.panels.accounts.memberPayments.list,
        icon: icons.AccountIcon2,
        description: "Lorem ipsum dolor sit",
      },
      {
        label: "Expenses",
        title: "Expenses",
        path: FRONTEND_LINKS.panels.accounts.expenses.list,
        icon: icons.AccountIcon2,
        description: "Lorem ipsum dolor sit",
      },
      {
        label: "Payee Banks",
        title: "Payee Banks",
        path: FRONTEND_LINKS.panels.accounts.bank.receive,
        icon: icons.AccountIcon2,
        description: "Lorem ipsum dolor sit",
      },
      {
        label: "Voucher",
        title: "Voucher",
        path: FRONTEND_LINKS.panels.accounts.vouchers.cash.index,
        icon: icons.AccountIcon2,
        description: "Lorem ipsum dolor sit",
      },
      {
        label: "Voucher Report",
        title: "Voucher Report",
        path: FRONTEND_LINKS.panels.accounts.vouchers.report.index,
        icon: icons.AccountIcon2,
        description: "Lorem ipsum dolor sit",
      },
      {
        label: "Trial Balance",
        title: "Trial Balance",
        path: FRONTEND_LINKS.panels.accounts.vouchers.trialBalance.index,
        icon: icons.AccountIcon2,
        description: "Trial Balance Report",
      },
      {
        label: "Income Statement",
        title: "Income Statement",
        path: FRONTEND_LINKS.panels.accounts.vouchers.incomeStatement.index,
        icon: icons.AccountIcon2,
        description: "Income State Report",
      },
      {
        label: "Balance Sheet",
        title: "Balance Sheet",
        path: FRONTEND_LINKS.panels.accounts.vouchers.balanceSheet.index,
        icon: icons.AccountIcon2,
        description: "Balance Sheet Report",
      },
    ],
    permission: "accounts",
  },
  {
    label: "Cash Card",
    children: [
      {
        label: "Cash Cards",
        title: "Cash Cards",
        path: FRONTEND_LINKS.panels.cashCard.entries.list,
        icon: icons.RfidIcon1,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Guest Cash Card Issues",
        title: "Member",
        path: FRONTEND_LINKS.panels.cashCard.entries.create,
        icon: icons.RfidIcon2,
        description: "RFID Smart Cash Card Issue From IT",
      },
      {
        label: "Guest Cash Card Issues",
        title: "Guest",
        path: FRONTEND_LINKS.panels.cashCard.issue,
        icon: icons.RfidIcon2,
        description: "RFID Smart Cash Card Issue From IT",
      },
      {
        label: "Cash Card Block",
        title: "Block",
        path: FRONTEND_LINKS.panels.cashCard.block,
        icon: icons.RfidIcon3,
        description: "RFID Smart Cash Card Block",
      },
      {
        label: "Cash Card Refill",
        title: "Refill",
        path: FRONTEND_LINKS.panels.cashCard.refill,
        icon: icons.RfidIcon6,
        description: "RFID Smart Cash Card Refill",
      },
      {
        label: "Cash Card Return",
        title: "Return",
        path: FRONTEND_LINKS.panels.cashCard.return,
        icon: icons.RfidIcon5,
        description: "RFID Smart Cash Card Return",
      },
      {
        label: "Card Statement",
        title: "Statement",
        path: FRONTEND_LINKS.panels.cashCard.report,
        icon: icons.RfidIcon4,
        description: "RFID Smart Cash Card Statement & Report",
      },
      // {
      //     label: "Virtual Card",
      //     title: "V.Card",
      //     path: FRONTEND_LINKS.panels.cashCard.virtual,
      //     icon: icons.RfidIcon4,
      //     description: "RFID Smart Cash Card Statement & Report",
      // },
    ],
    permission: "refill_smart_cash_card",
  },
  {
    label: "Hotel Management",
    children: [
      {
        label: "Reservations",
        title: "Reservations",
        path: FRONTEND_LINKS.panels.hotelManagement.guests.list,
        icon: icons.HotelIcon1,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Room Reservations",
        title: "Room Reservations",
        path: FRONTEND_LINKS.panels.hotelManagement.reservations.create,
        icon: icons.HotelIcon2,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Room Check In",
        title: "Check In",
        path: FRONTEND_LINKS.panels.hotelManagement.checkIn.list,
        icon: icons.HotelIcon4,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Room Check Out",
        title: "Check Out",
        path: FRONTEND_LINKS.panels.hotelManagement.checkOut.list,
        icon: icons.HotelIcon5,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Sales Report",
        title: "Sales Report",
        path: FRONTEND_LINKS.panels.hotelManagement.salesReport.list,
        icon: icons.HotelIcon6,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
    ],
    permission: "hotel_management",
  },
  {
    label: "System",
    children: [
      {
        label: "Voucher Configure",
        title: "Voucher",
        path: FRONTEND_LINKS.panels.system.voucherConfigures,
        icon: icons.SystemIcon7,
        description: "Lorem ipsum dolor sit amet consectetur",
      },

      {
        label: "Site Settings",
        title: "Site Settings",
        path: FRONTEND_LINKS.panels.system.siteConfig,
        icon: icons.SystemIcon8,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Permissions",
        title: "Permissions",
        path: FRONTEND_LINKS.panels.system.permissions,
        icon: icons.SystemIcon1,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Roles",
        title: "Roles",
        path: FRONTEND_LINKS.panels.system.roles,
        icon: icons.SystemIcon2,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Printers",
        title: "Printers",
        path: FRONTEND_LINKS.panels.system.printers,
        icon: icons.SystemIcon2,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      // {
      //     label: "Project Entry",
      //     path: "system/project-entries",
      //     icon: icons.SystemIcon2,
      //     description: "Lorem ipsum dolor sit amet consectetur",
      // },
      // {
      //     label: "Price Change Circular",
      //     path: "system/price-changes",
      //     icon: icons.SystemIcon3,
      //     description: "Lorem ipsum dolor sit amet consectetur",
      // },
      // {
      //     label: "Company",
      //     path: "system/company",
      //     icon: icons.SystemIcon4,
      //     description: "Lorem ipsum dolor sit amet consectetur",
      // },
      // {
      //     label: "Branches",
      //     path: "system/branches",
      //     icon: icons.SystemIcon5,
      //     description: "Lorem ipsum dolor sit amet consectetur",
      // },
    ],
    permission: "settings",
  },

  {
    label: "Inventory",
    children: [
      {
        label: "Suppliers Types",
        title: "Types",
        path: FRONTEND_LINKS.panels.inventory.manageSuppliers.supplierTypes
          .list,
        icon: icons.PosIcon2,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Suppliers",
        title: "Suppliers",
        path: FRONTEND_LINKS.panels.inventory.manageSuppliers.suppliers.list,
        icon: icons.PosIcon2,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Internal Requisitions",
        title: "Requisitions",
        path: FRONTEND_LINKS.panels.inventory.requisitions.list,
        icon: icons.PosIcon3,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Purchase Requests",
        title: "Requests",
        path: FRONTEND_LINKS.panels.inventory.requests.list,
        icon: icons.PosIcon4,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Purchase Orders",
        title: "Orders",
        path: FRONTEND_LINKS.panels.inventory.orders.list,
        icon: icons.PosIcon5,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Product Receives",
        title: "Receives",
        path: FRONTEND_LINKS.panels.inventory.receives.list,
        icon: icons.PosIcon6,
        description: "Lorem ipsum dolor sit amet consectetur",
      },

      {
        label: "Requisition Wise Product Distribution",
        title: "Distribution",
        path: FRONTEND_LINKS.panels.inventory.productDistribution.list,
        icon: icons.productDistribution,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Product Return to Supplier",
        title: "Supplier",
        path: FRONTEND_LINKS.panels.inventory.productReturnToSupplier.list,
        icon: icons.supplier,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Damage/Loss Return",
        title: "Loss Return",
        path: FRONTEND_LINKS.panels.inventory.damageLossReturn.list,
        icon: icons.damage,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Damage/Loss Expired Product Entry",
        title: "Damaged/Loss",
        path: FRONTEND_LINKS.panels.inventory.damageLossExpiredProductEntry
          .list,
        icon: icons.loss,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Product Return to Store From Department",
        title: "Store Return",
        path: FRONTEND_LINKS.panels.inventory.productReturnToStoreFromDepartment
          .list,
        icon: icons.returnIcon,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Warehouse",
        title: "Warehouse",
        path: FRONTEND_LINKS.panels.inventory.warehouse.list,
        icon: icons.warehouse,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Production Receive",
        title: "Production Receive",
        path: FRONTEND_LINKS.panels.inventory.productionReceive.list,
        icon: icons.receive,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Product Consumption",
        title: "Product Consumption",
        path: FRONTEND_LINKS.panels.inventory.productComsumption.list,
        icon: icons.consumption,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Inventory Report",
        title: "Inventory Report",
        path: FRONTEND_LINKS.panels.inventory.report.index,
        icon: icons.report,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
    ],
    permission: "inventory",
  },
  {
    label: "Payroll",
    children: [
      {
        label: "Salary Making (singleID Wise)",
        title: "Salary Making",
        path: FRONTEND_LINKS.panels.payroll.salaryMaking.create,
        icon: icons.salaryMaking,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Allowance/Deduction Entry",
        title: "Allowance/Deduction Entry",
        path: FRONTEND_LINKS.panels.payroll.allowanceEntry.create,
        icon: icons.allowanceEntry,
        description: "Lorem ipsum dolor sit amet consectetur",
      },

      {
        label: "PF Loan Issue",
        title: "PF Loan Issue",
        path: FRONTEND_LINKS.panels.payroll.pfLoanIssue.create,
        icon: icons.pfLoanIssue,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "PF Loan Categories",
        title: "PF Loan Categories",
        path: FRONTEND_LINKS.panels.payroll.pfLoanCategories.create,
        icon: icons.pfLoanIssue,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "PF Loan Adjustment(Monthly With Salary)",
        title: "PF Loan Adjustment",
        path: FRONTEND_LINKS.panels.payroll.pfLoanAdjustment.create,
        icon: icons.pfLoanAdjustment,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "PF Loan Cash Adjustment",
        title: "Cash Adjustment",
        path: FRONTEND_LINKS.panels.payroll.pfLoanCashAdjustment.create,
        icon: icons.pfLoanCashAdjustment,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "PF Loan Adjustment Details",
        title: "Adjust Details",
        path: FRONTEND_LINKS.panels.payroll.pfLoanAdjustDetails.create,
        icon: icons.pfLoanAdjustDetails,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Penalty/Club Fund Loan",
        title: "Club Fund Loan",
        path: FRONTEND_LINKS.panels.payroll.clubFundLoan.create,
        icon: icons.clubFundLoan,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Penalty/Club Fund Loan Adjustment",
        title: "Club Fund Loan Adjustment",
        path: FRONTEND_LINKS.panels.payroll.clubFundLoanAdjustment.create,
        icon: icons.clubFundLoanAdjustment,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Profident Fund General Ledger",
        title: "General Ledger",
        path: FRONTEND_LINKS.panels.payroll.profidentFundGeneralLedger.create,
        icon: icons.profidentFundGeneralLedger,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Pay Scale",
        title: "Pay Scale",
        path: FRONTEND_LINKS.panels.payroll.payscale.index,
        icon: icons.profidentFundClosingEntry,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Over Time and Extra Duty Entry",
        title: "Over Time Entry",
        path: FRONTEND_LINKS.panels.payroll.overTimeEntry.create,
        icon: icons.overTimeEntry,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Bonus",
        title: "Bonus",
        path: FRONTEND_LINKS.panels.payroll.bonus.index,
        icon: icons.bonus,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Type of Allowance and Deduction",
        title: "Allowance and Deduction",
        path: FRONTEND_LINKS.panels.payroll.typeOfAllowanceAndDeduction.create,
        icon: icons.typeOfAllowanceAndDeduction,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Employee Wise Basic Allowance and Deduction Setup",
        title: "Allowance and Deduction",
        path: FRONTEND_LINKS.panels.payroll
          .employeeWiseBasicAllowanceDeductionSetup.create,
        icon: icons.employeeWiseBasicAllowanceDeductionSetup,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Provident Fund Ledger Interest Entry",
        title: "Provident Fund Ledger Interest Entry",
        path: FRONTEND_LINKS.panels.payroll.providentFundLedgerInterestEntry
          .create,
        icon: icons.providentFundLedgerInterestEntry,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Provident Fund Report",
        title: "Provident Fund Report",
        path: FRONTEND_LINKS.panels.payroll.providentFundReport.create,
        icon: icons.providentFundReport,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
    ],
    permission: "payroll",
  },
  {
    label: "Attendance",
    children: [
      {
        label: "Employee Id Wise Manual Attendance",
        title: "Employee Id Wise Manual Attendance",
        path: FRONTEND_LINKS.panels.attendance.employeeIdWiseManualAttendance
          .create,
        icon: icons.leave10,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Late Consideration",
        title: "Late Consideration",
        path: FRONTEND_LINKS.panels.attendance.lateConsideration.create,
        icon: icons.lateConsideration,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Extra Punch Delete",
        title: "Extra Punch Delete",
        path: FRONTEND_LINKS.panels.attendance.extraPunchDelete.create,
        icon: icons.extraPunchDelete,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Holiday Calender Setup",
        title: "Holiday Calender Setup",
        path: FRONTEND_LINKS.panels.attendance.holidayCalenderSetup.create,
        icon: icons.holidayCalenderSetup,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Shifts ",
        title: "Shifts",
        path: FRONTEND_LINKS.panels.attendance.shiftSetup.create,
        icon: icons.shift,
        description: "Shift Setup",
      },
      {
        label: "Leave Entry",
        title: "Leave Entry",
        path: FRONTEND_LINKS.panels.attendance.leave.leaveEntry.index,
        icon: icons.leave1,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Leave Details",
        title: "Leave Details",
        path: FRONTEND_LINKS.panels.attendance.leave.leaveDetails.create,
        icon: icons.leave2,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Opening Leave Entry",
        title: "Opening Leave Entry",
        path: FRONTEND_LINKS.panels.attendance.leave.openingLeaveEntry.create,
        icon: icons.leave3,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Leave Report",
        title: "Leave Report",
        path: FRONTEND_LINKS.panels.attendance.leave.leaveReport.create,
        icon: icons.leave4,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Leave Inlieu Entry",
        title: "Leave Inlieu Entry",
        path: FRONTEND_LINKS.panels.attendance.leave.leaveInlieuEntry.create,
        icon: icons.leave5,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Leave Encashment",
        title: "Leave Encashment",
        path: FRONTEND_LINKS.panels.attendance.leave.leaveEncashment.create,
        icon: icons.leave6,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Leave Form",
        title: "Leave Form",
        path: FRONTEND_LINKS.panels.attendance.leave.leaveForm.create,
        icon: icons.leave7,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Leave Setup",
        title: "Leave Setup",
        path: FRONTEND_LINKS.panels.attendance.leave.leaveSetup.create,
        icon: icons.leave8,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Roster Setup",
        title: "Roster Setup",
        path: FRONTEND_LINKS.panels.attendance.rosterSetup.create,
        icon: icons.leave9,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Attendance Device Database Synchronization",
        title: "Attendance Device Database Synchronization",
        path: FRONTEND_LINKS.panels.attendance
          .attendanceDeviceDatabaseSynchronization.create,
        icon: icons.employeeIdWiseManualAttendance,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
      {
        label: "Grace Period Setup",
        title: "Grace Period Setup",
        path: FRONTEND_LINKS.panels.attendance.gracePeriodSetup.create,
        icon: icons.leave11,
        description: "Lorem ipsum dolor sit amet consectetur",
      },
    ],
    permission: "attendance",
  },
];

export const sideMenu = [
  {
    label: "Dashboard",
    path: FRONTEND_LINKS.panels.dashboard,
    icon: icons.AnalyticsIcon1,
    permission: "view_dashboard",
  },
  {
    label: "Product Management",
    path: FRONTEND_LINKS.panels.manageProducts.products.list,
    icon: icons.ProductIcon7,
    permission: "manage_products",
  },
  {
    label: "POS",
    path: FRONTEND_LINKS.panels.pointOfSale.sales.create,
    icon: icons.PosIcon7,
    permission: "pos",
  },
  {
    label: "CRM",
    path: FRONTEND_LINKS.panels.customerRelationManagement.members.list,
    icon: icons.CrmIcon4,
    permission: "crm",
  },
  {
    label: "HRM",
    path: FRONTEND_LINKS.panels.humanResourceManagement.employees.list,
    icon: icons.HrmIcon5,
    permission: "hrm",
  },
  {
    label: "Accounts",
    path: FRONTEND_LINKS.panels.accounts.chartOfAccounts.list,
    icon: icons.AccountIcon3,
    permission: "accounts",
  },
  {
    label: "Refill Smart Cash Card",
    path: FRONTEND_LINKS.panels.cashCard.entries.list,
    icon: icons.RfidIcon1,
    permission: "refill_smart_cash_card",
  },
  {
    label: "Hotel Management",
    path: FRONTEND_LINKS.panels.hotelManagement.guests.list,
    icon: icons.HotelIcon2,
    permission: "hotel_management",
  },
  {
    label: "Inventory",
    path: FRONTEND_LINKS.panels.inventory.manageSuppliers.supplierTypes.list,
    icon: icons.inventory,
    permission: "inventory",
  },
  {
    label: "Payroll",
    path: FRONTEND_LINKS.panels.payroll.salaryMaking.create,
    icon: icons.salaryMaking,
    permission: "payroll",
  },
  {
    label: "Attendance",
    path: FRONTEND_LINKS.panels.attendance.employeeIdWiseManualAttendance
      .create,
    icon: icons.leave10,
    permission: "attendance",
  },
  {
    label: "Settings",
    path: FRONTEND_LINKS.panels.system.voucherConfigures,
    icon: icons.SystemIcon6,
    permission: "settings",
  },
];
